/*
 * Auto-generated by MemoryHTVisualizerRunner.
 * Do not edit manually; run the runner again instead.
 */
window.MEMORY_HT_EXPERIMENTS = [
  {
    id: "SEA_ABRUPT",
    label: "SEA — Abrupt recurring (G1)",
    category: "Systematic synthetic suite",
    file: "data/SEA_ABRUPT.js",
    default: true
  },
  {
    id: "HYPERPLANE_RECURRING",
    label: "Hyperplane — Abrupt recurring (G2)",
    category: "Systematic synthetic suite",
    file: "data/HYPERPLANE_RECURRING.js",
    default: false
  },
  {
    id: "RANDOM_RBF_RECURRING",
    label: "RandomRBF — Abrupt recurring (G3)",
    category: "Systematic synthetic suite",
    file: "data/RANDOM_RBF_RECURRING.js",
    default: false
  },
  {
    id: "RANDOM_TREE_RECURRING",
    label: "RandomTree — Abrupt recurring (G4)",
    category: "Systematic synthetic suite",
    file: "data/RANDOM_TREE_RECURRING.js",
    default: false
  },
  {
    id: "SEA_GRADUAL_W5000",
    label: "SEA — Gradual recurring (G5, w=5000)",
    category: "Systematic synthetic suite",
    file: "data/SEA_GRADUAL_W5000.js",
    default: false
  },
  {
    id: "SEA_ABRUPT_NOISE10",
    label: "SEA — Abrupt recurring + 10% noise (G6)",
    category: "Systematic synthetic suite",
    file: "data/SEA_ABRUPT_NOISE10.js",
    default: false
  },
  {
    id: "RANDOM_RBF_GRADUAL_W5000",
    label: "RandomRBF — Gradual recurring (G7, w=5000)",
    category: "Systematic synthetic suite",
    file: "data/RANDOM_RBF_GRADUAL_W5000.js",
    default: false
  },
  {
    id: "ELECTRICITY",
    label: "Electricity",
    category: "Real-world datasets",
    file: "data/ELECTRICITY.js",
    default: false
  },
  {
    id: "AIRLINES",
    label: "Airlines",
    category: "Real-world datasets",
    file: "data/AIRLINES.js",
    default: false
  }
];
